# Generated by Django 4.1.4 on 2023-06-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('FT', 'Filtro'), ('FA', 'Filtro de Ar'), ('FB', 'Filtro Combustível'), ('OM', 'Óleo de Motor'), ('MT', 'Motor'), ('CA', 'Cabeçote'), ('JU', 'Junta'), ('EMB', 'Embreagem'), ('AM', 'Amortecedor'), ('BAN', 'Bandeja'), ('PIV', 'Pivô'), ('TER', 'Terminal'), ('BA', 'Barra Axial'), ('CX', 'Caixa'), ('BC', 'Bucha'), ('CM', 'Coxim Motor'), ('CC', 'Coxim Câmbio'), ('PA', 'Pastilha'), ('DC', 'Disco'), ('CL', 'Cilindro'), ('MAN', 'Mangueira'), ('VA', 'Válvula'), ('CAN', 'Cano'), ('FIT', 'Freio Traz'), ('CDR', 'Cilindro de Roda'), ('BDA', "Bomba d'água"), ('BOC', 'Bomba Combustível'), ('ROD', 'Rolamento Dianteiro'), ('ROT', 'Rolamento Traseiro'), ('COF', 'Coifa'), ('HOM', 'Homocinética'), ('LB', 'Limpeza Bicos'), ('SCI', 'Scanner de Injeção'), ('AG', 'Água'), ('ADT', 'Aditivo'), ('VT', 'Válvula Termostática'), ('COD', 'Correia Dentada'), ('ROL', 'Rolamento'), ('VL', 'Vela'), ('CB', 'Cabo'), ('BO', 'Bobina')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateTimeField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocole', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_manutencao', models.ManyToManyField(to='servicos.categoriamanutencao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
