# Generated by Django 4.1.4 on 2023-06-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_whatsapp'),
        ('servicos', '0003_servico_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.carro'),
        ),
    ]
